DougFinalProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DougFinalProject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DougFinalProject/Controllers/Projects1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DougFinalProject.Models;

namespace DougFinalProject.Controllers
{
    public class Projects1Controller : Controller
    {
        private DougFinalProjectDBEntities db = new DougFinalProjectDBEntities();

        // GET: Projects1
        public ActionResult Index()
        {
            return View(db.Projects.ToList());
        }

        // GET: Projects1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projects1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjectID,ProjectName,Thumbnail,Description,GitHubLink")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Projects.Add(project);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(project);
        }

        // GET: Projects1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProjectID,ProjectName,Thumbnail,Description,GitHubLink")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(project);
        }

        // GET: Projects1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DougFinalProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>
<address>
    <strong>Bio: Doug O'Bryon  </strong><br><br />
Experienced MBA specializing in Big Data, pattern recognition, technical writing, and industry research and evaluation. 
Published author featuring over 100 books, whitepapers, articles, and business plans. Recently completed intensive WeCanCodeIT boot-camp focusing
on C#, .NET, CSS, MVC, BootStrap, GitHub, and SQL.<br /><br />
    <strong>Skills:</strong><br /><br />
Software Engineer/Junior Developer with experience in C#, .NET, CSS, MVC, BootStrap, GitHub, and SQL<br />
Technical Writing<br />
Strategic Planning<br />
Market Research<br />
Big Data Capture/Interpretation<br /> 
Content Development<br /> 
Published Author<br />
Keynote Speaker<br />
Project Leadership<br /><br /> 
    <strong>Email: </strong><a href="mailto:dougobryon@gmail.com">dougobryon@gmail.com</a><br />
    <strong>LinkedIn: </strong>   <a href="https://www.linkedin.com/in/douglasobryon">https://www.linkedin.com/in/douglasobryon</a><br />
    <strong>Twitter: </strong><a href="https://twitter.com/DougOBryon">https://twitter.com/DougOBryon</a><br />
    <strong>GitHub:  </strong> <a href="https://github.com/Dougobryon">https://github.com/Dougobryon</a><br />
    <strong>Website:  </strong> <a href="http://www.dougobryon.com/">http://www.dougobryon.com/</a><br />
    <strong>Book: "Specialist Nation - A Survival Guide for America"  </strong> <a href="http://www.amazon.com/dp/B00CNUW846">http://www.amazon.com/dp/B00CNUW846</a><br />

DougFinalProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Doug Doug O'Bryon</h3>
<address>
    17183 Park Lane Drive <br />
    Strongsville, Ohio  44136<br />
    <abbr title="Phone">P:</abbr>
    443-421-0167
</address>
<address>
    <strong>LinkedIn:</strong>   <a href="mailto:https://www.linkedin.com/in/douglasobryon">https://www.linkedin.com/in/douglasobryon</a><br />
    <strong>GitHub:  </strong> <a href="https://github.com/Dougobryon">https://github.com/Dougobryon</a><br />
    <strong>Website:  </strong> <a href="http://www.dougobryon.com/">http://www.dougobryon.com/</a>
</address>

DougFinalProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    ViewBag.BodyClass = "homepage";
}
<div class="jumbotron">
    <h1>Bootcamp Projects: A Retrospective</h1>
    <p class="lead">The enclosed programs feature a showcase of projects completed during the 2016 WeCanCodeIT Bootcamp</p>
</div><br /><br /><br /><br /><br /><br /><br />
<div class="row">
<div class="col-md-4">
    <h2>@Html.ActionLink("PROJECTS", "Index", "Projects1")</h2>
    <p>
            A sampling of select software programs sequenced throughout the Spring 2016 cohort from basic to more advanced.
    </p>
</div>
</div>